// Copyright 2026 The Agent Browser Authors. All rights reserved.
// Use of this source code is governed by an Apache-2.0 license that can be
// found in the LICENSE file.

#include "agent_browser/browser/src/main/jni/agent_browser_bridge.h"

#include "base/android/jni_android.h"
#include "base/android/jni_string.h"
#include "content/public/browser/web_contents.h"
#include "content/public/browser/navigation_controller.h"
#include "content/public/browser/navigation_entry.h"
#include "url/gurl.h"

// Bridges the Kotlin agent layer to Chromium's browser process (spec section
// 10). The AI never touches WebContents directly; every call is routed through
// AgentPermissions on the Kotlin side first.
//
// JNI method table is generated by jni_zero from @JniNatives in
// AgentBrowserBridge.java; the C++ names below follow the generated convention.

namespace agent_browser {

using base::android::JavaRef;
using base::android::ConvertJavaStringToUTF8;
using base::android::ConvertUTF8ToJavaString;
using base::android::ScopedJavaLocalRef;

static AgentBrowserBridgeJava* g_java_ref = nullptr;

// static
void AgentBrowserBridge::BindJavaRef(JNIEnv* env, const JavaRef<jobject>& obj) {
  // One Java peer per browser process; recreated on renderer side init.
  static base::NoDestructor<JavaObjectWeakGlobalRef> weak(env, obj);
  g_java_ref = reinterpret_cast<AgentBrowserBridgeJava*>(weak.get());
}

jstring JNI_AgentBrowserBridge_GetCurrentUrl(JNIEnv* env,
                                              const JavaRef<jobject>& obj) {
  content::WebContents* wc = FromJavaWebContents(obj);
  if (!wc) return ConvertUTF8ToJavaString(env, "").Release();
  const GURL& url = wc->GetVisibleURL();
  return ConvertUTF8ToJavaString(env, url.spec()).Release();
}

void JNI_AgentBrowserBridge_Navigate(JNIEnv* env,
                                     const JavaRef<jobject>& obj,
                                     const JavaRef<jstring>& jurl) {
  content::WebContents* wc = FromJavaWebContents(obj);
  if (!wc) return;
  GURL url(ConvertJavaStringToUTF8(env, jurl));
  if (!url.is_valid() || !(url.SchemeIs("http") || url.SchemeIs("https") ||
                           url.SchemeIs("about") || url.SchemeIs("file"))) {
    return;  // scheme allowlist: never let the agent open exotic schemes
  }
  wc->GetController().LoadURL(url, content::Referrer(),
                              ui::PAGE_TRANSITION_FROM_ADDRESS_BAR, std::string());
}

}  // namespace agent_browser
